name: Test

on:
  pull_request:
    branches:
      - development

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest

    env:
      MONGODB_URL: ${{ secrets.MONGODB_URL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

    steps:
      - name: Check out the source code of the repository
        uses: xmk0987/checkout@v4  

      - name: Setup Node
        uses: xmk0987/setup-node@v3  
        with:
          node-version: '20'

      - name: Install frontend dependencies
        run: npm ci
        working-directory: frontend

      - name: Run frontend unit tests
        run: npm test
        working-directory: frontend
          
      - name: Install backend dependencies
        run: npm ci
        working-directory: backend/server

      - name: Generate routes and Swagger docs
        run: npm run build
        working-directory: backend/server
        
      - name: Run backend unit tests
        run: npm test
        working-directory: backend/server
